// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.5.1
// source: mst.proto

package rpc

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type MSTChild struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	High  []byte `protobuf:"bytes,3,opt,name=high,proto3" json:"high,omitempty"`
}

func (x *MSTChild) Reset() {
	*x = MSTChild{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mst_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MSTChild) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MSTChild) ProtoMessage() {}

func (x *MSTChild) ProtoReflect() protoreflect.Message {
	mi := &file_mst_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MSTChild.ProtoReflect.Descriptor instead.
func (*MSTChild) Descriptor() ([]byte, []int) {
	return file_mst_proto_rawDescGZIP(), []int{0}
}

func (x *MSTChild) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *MSTChild) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *MSTChild) GetHigh() []byte {
	if x != nil {
		return x.High
	}
	return nil
}

type MSTNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Level    uint32      `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	Low      []byte      `protobuf:"bytes,2,opt,name=low,proto3" json:"low,omitempty"`
	Children []*MSTChild `protobuf:"bytes,3,rep,name=children,proto3" json:"children,omitempty"`
}

func (x *MSTNode) Reset() {
	*x = MSTNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mst_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MSTNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MSTNode) ProtoMessage() {}

func (x *MSTNode) ProtoReflect() protoreflect.Message {
	mi := &file_mst_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MSTNode.ProtoReflect.Descriptor instead.
func (*MSTNode) Descriptor() ([]byte, []int) {
	return file_mst_proto_rawDescGZIP(), []int{1}
}

func (x *MSTNode) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *MSTNode) GetLow() []byte {
	if x != nil {
		return x.Low
	}
	return nil
}

func (x *MSTNode) GetChildren() []*MSTChild {
	if x != nil {
		return x.Children
	}
	return nil
}

type MSTPutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   uint32 `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Value uint32 `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *MSTPutRequest) Reset() {
	*x = MSTPutRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mst_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MSTPutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MSTPutRequest) ProtoMessage() {}

func (x *MSTPutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mst_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MSTPutRequest.ProtoReflect.Descriptor instead.
func (*MSTPutRequest) Descriptor() ([]byte, []int) {
	return file_mst_proto_rawDescGZIP(), []int{2}
}

func (x *MSTPutRequest) GetKey() uint32 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *MSTPutRequest) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type MSTGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key uint32 `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *MSTGetRequest) Reset() {
	*x = MSTGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mst_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MSTGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MSTGetRequest) ProtoMessage() {}

func (x *MSTGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mst_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MSTGetRequest.ProtoReflect.Descriptor instead.
func (*MSTGetRequest) Descriptor() ([]byte, []int) {
	return file_mst_proto_rawDescGZIP(), []int{3}
}

func (x *MSTGetRequest) GetKey() uint32 {
	if x != nil {
		return x.Key
	}
	return 0
}

type MSTGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value uint32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *MSTGetResponse) Reset() {
	*x = MSTGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mst_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MSTGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MSTGetResponse) ProtoMessage() {}

func (x *MSTGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mst_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MSTGetResponse.ProtoReflect.Descriptor instead.
func (*MSTGetResponse) Descriptor() ([]byte, []int) {
	return file_mst_proto_rawDescGZIP(), []int{4}
}

func (x *MSTGetResponse) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type MSTGossipRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RootHash []byte `protobuf:"bytes,1,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"`
}

func (x *MSTGossipRequest) Reset() {
	*x = MSTGossipRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mst_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MSTGossipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MSTGossipRequest) ProtoMessage() {}

func (x *MSTGossipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mst_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MSTGossipRequest.ProtoReflect.Descriptor instead.
func (*MSTGossipRequest) Descriptor() ([]byte, []int) {
	return file_mst_proto_rawDescGZIP(), []int{5}
}

func (x *MSTGossipRequest) GetRootHash() []byte {
	if x != nil {
		return x.RootHash
	}
	return nil
}

type MSTGetNodesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hashes [][]byte `protobuf:"bytes,1,rep,name=hashes,proto3" json:"hashes,omitempty"`
}

func (x *MSTGetNodesRequest) Reset() {
	*x = MSTGetNodesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mst_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MSTGetNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MSTGetNodesRequest) ProtoMessage() {}

func (x *MSTGetNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mst_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MSTGetNodesRequest.ProtoReflect.Descriptor instead.
func (*MSTGetNodesRequest) Descriptor() ([]byte, []int) {
	return file_mst_proto_rawDescGZIP(), []int{6}
}

func (x *MSTGetNodesRequest) GetHashes() [][]byte {
	if x != nil {
		return x.Hashes
	}
	return nil
}

type MSTGetNodesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodes []*MSTNode `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
}

func (x *MSTGetNodesResponse) Reset() {
	*x = MSTGetNodesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mst_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MSTGetNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MSTGetNodesResponse) ProtoMessage() {}

func (x *MSTGetNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mst_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MSTGetNodesResponse.ProtoReflect.Descriptor instead.
func (*MSTGetNodesResponse) Descriptor() ([]byte, []int) {
	return file_mst_proto_rawDescGZIP(), []int{7}
}

func (x *MSTGetNodesResponse) GetNodes() []*MSTNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

var File_mst_proto protoreflect.FileDescriptor

var file_mst_proto_rawDesc = []byte{
	0x0a, 0x09, 0x6d, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x76, 0x75, 0x6c,
	0x74, 0x75, 0x72, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x72, 0x70, 0x63,
	0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x46, 0x0a,
	0x08, 0x4d, 0x53, 0x54, 0x43, 0x68, 0x69, 0x6c, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x69, 0x67, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x68, 0x69, 0x67, 0x68, 0x22, 0x6c, 0x0a, 0x07, 0x4d, 0x53, 0x54, 0x4e, 0x6f, 0x64, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x77, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x03, 0x6c, 0x6f, 0x77, 0x12, 0x39, 0x0a, 0x08, 0x63, 0x68, 0x69, 0x6c,
	0x64, 0x72, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x76, 0x75, 0x6c,
	0x74, 0x75, 0x72, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x72, 0x70, 0x63,
	0x2e, 0x4d, 0x53, 0x54, 0x43, 0x68, 0x69, 0x6c, 0x64, 0x52, 0x08, 0x63, 0x68, 0x69, 0x6c, 0x64,
	0x72, 0x65, 0x6e, 0x22, 0x37, 0x0a, 0x0d, 0x4d, 0x53, 0x54, 0x50, 0x75, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x21, 0x0a, 0x0d,
	0x4d, 0x53, 0x54, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22,
	0x26, 0x0a, 0x0e, 0x4d, 0x53, 0x54, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x2f, 0x0a, 0x10, 0x4d, 0x53, 0x54, 0x47, 0x6f,
	0x73, 0x73, 0x69, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x72,
	0x6f, 0x6f, 0x74, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08,
	0x72, 0x6f, 0x6f, 0x74, 0x48, 0x61, 0x73, 0x68, 0x22, 0x2c, 0x0a, 0x12, 0x4d, 0x53, 0x54, 0x47,
	0x65, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x68, 0x61, 0x73, 0x68, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x06,
	0x68, 0x61, 0x73, 0x68, 0x65, 0x73, 0x22, 0x49, 0x0a, 0x13, 0x4d, 0x53, 0x54, 0x47, 0x65, 0x74,
	0x4e, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a,
	0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x76,
	0x75, 0x6c, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x72,
	0x70, 0x63, 0x2e, 0x4d, 0x53, 0x54, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65,
	0x73, 0x32, 0xa3, 0x01, 0x0a, 0x0a, 0x4d, 0x53, 0x54, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x43, 0x0a, 0x03, 0x50, 0x75, 0x74, 0x12, 0x22, 0x2e, 0x76, 0x75, 0x6c, 0x74, 0x75, 0x72,
	0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x53,
	0x54, 0x50, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x50, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x22, 0x2e, 0x76,
	0x75, 0x6c, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x72,
	0x70, 0x63, 0x2e, 0x4d, 0x53, 0x54, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x23, 0x2e, 0x76, 0x75, 0x6c, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x53, 0x54, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x32, 0xbf, 0x01, 0x0a, 0x11, 0x4d, 0x53, 0x54, 0x4d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x49, 0x0a,
	0x06, 0x47, 0x6f, 0x73, 0x73, 0x69, 0x70, 0x12, 0x25, 0x2e, 0x76, 0x75, 0x6c, 0x74, 0x75, 0x72,
	0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x53,
	0x54, 0x47, 0x6f, 0x73, 0x73, 0x69, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x5f, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x4e,
	0x6f, 0x64, 0x65, 0x73, 0x12, 0x27, 0x2e, 0x76, 0x75, 0x6c, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x53, 0x54, 0x47, 0x65,
	0x74, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e,
	0x76, 0x75, 0x6c, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x72, 0x70, 0x63, 0x2e, 0x4d, 0x53, 0x54, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x76, 0x75, 0x6c, 0x74, 0x75, 0x72, 0x65, 0x64,
	0x62, 0x2f, 0x76, 0x75, 0x6c, 0x74, 0x75, 0x72, 0x65, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2f, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mst_proto_rawDescOnce sync.Once
	file_mst_proto_rawDescData = file_mst_proto_rawDesc
)

func file_mst_proto_rawDescGZIP() []byte {
	file_mst_proto_rawDescOnce.Do(func() {
		file_mst_proto_rawDescData = protoimpl.X.CompressGZIP(file_mst_proto_rawDescData)
	})
	return file_mst_proto_rawDescData
}

var file_mst_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_mst_proto_goTypes = []interface{}{
	(*MSTChild)(nil),            // 0: vulture.service.rpc.MSTChild
	(*MSTNode)(nil),             // 1: vulture.service.rpc.MSTNode
	(*MSTPutRequest)(nil),       // 2: vulture.service.rpc.MSTPutRequest
	(*MSTGetRequest)(nil),       // 3: vulture.service.rpc.MSTGetRequest
	(*MSTGetResponse)(nil),      // 4: vulture.service.rpc.MSTGetResponse
	(*MSTGossipRequest)(nil),    // 5: vulture.service.rpc.MSTGossipRequest
	(*MSTGetNodesRequest)(nil),  // 6: vulture.service.rpc.MSTGetNodesRequest
	(*MSTGetNodesResponse)(nil), // 7: vulture.service.rpc.MSTGetNodesResponse
	(*empty.Empty)(nil),         // 8: google.protobuf.Empty
}
var file_mst_proto_depIdxs = []int32{
	0, // 0: vulture.service.rpc.MSTNode.children:type_name -> vulture.service.rpc.MSTChild
	1, // 1: vulture.service.rpc.MSTGetNodesResponse.nodes:type_name -> vulture.service.rpc.MSTNode
	2, // 2: vulture.service.rpc.MSTService.Put:input_type -> vulture.service.rpc.MSTPutRequest
	3, // 3: vulture.service.rpc.MSTService.Get:input_type -> vulture.service.rpc.MSTGetRequest
	5, // 4: vulture.service.rpc.MSTManagerService.Gossip:input_type -> vulture.service.rpc.MSTGossipRequest
	6, // 5: vulture.service.rpc.MSTManagerService.GetNodes:input_type -> vulture.service.rpc.MSTGetNodesRequest
	8, // 6: vulture.service.rpc.MSTService.Put:output_type -> google.protobuf.Empty
	4, // 7: vulture.service.rpc.MSTService.Get:output_type -> vulture.service.rpc.MSTGetResponse
	8, // 8: vulture.service.rpc.MSTManagerService.Gossip:output_type -> google.protobuf.Empty
	7, // 9: vulture.service.rpc.MSTManagerService.GetNodes:output_type -> vulture.service.rpc.MSTGetNodesResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_mst_proto_init() }
func file_mst_proto_init() {
	if File_mst_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mst_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MSTChild); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mst_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MSTNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mst_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MSTPutRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mst_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MSTGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mst_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MSTGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mst_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MSTGossipRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mst_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MSTGetNodesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mst_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MSTGetNodesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mst_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_mst_proto_goTypes,
		DependencyIndexes: file_mst_proto_depIdxs,
		MessageInfos:      file_mst_proto_msgTypes,
	}.Build()
	File_mst_proto = out.File
	file_mst_proto_rawDesc = nil
	file_mst_proto_goTypes = nil
	file_mst_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MSTServiceClient is the client API for MSTService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MSTServiceClient interface {
	Put(ctx context.Context, in *MSTPutRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	Get(ctx context.Context, in *MSTGetRequest, opts ...grpc.CallOption) (*MSTGetResponse, error)
}

type mSTServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMSTServiceClient(cc grpc.ClientConnInterface) MSTServiceClient {
	return &mSTServiceClient{cc}
}

func (c *mSTServiceClient) Put(ctx context.Context, in *MSTPutRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/vulture.service.rpc.MSTService/Put", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mSTServiceClient) Get(ctx context.Context, in *MSTGetRequest, opts ...grpc.CallOption) (*MSTGetResponse, error) {
	out := new(MSTGetResponse)
	err := c.cc.Invoke(ctx, "/vulture.service.rpc.MSTService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MSTServiceServer is the server API for MSTService service.
type MSTServiceServer interface {
	Put(context.Context, *MSTPutRequest) (*empty.Empty, error)
	Get(context.Context, *MSTGetRequest) (*MSTGetResponse, error)
}

// UnimplementedMSTServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMSTServiceServer struct {
}

func (*UnimplementedMSTServiceServer) Put(context.Context, *MSTPutRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Put not implemented")
}
func (*UnimplementedMSTServiceServer) Get(context.Context, *MSTGetRequest) (*MSTGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterMSTServiceServer(s *grpc.Server, srv MSTServiceServer) {
	s.RegisterService(&_MSTService_serviceDesc, srv)
}

func _MSTService_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MSTPutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MSTServiceServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vulture.service.rpc.MSTService/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MSTServiceServer).Put(ctx, req.(*MSTPutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MSTService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MSTGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MSTServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vulture.service.rpc.MSTService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MSTServiceServer).Get(ctx, req.(*MSTGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MSTService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "vulture.service.rpc.MSTService",
	HandlerType: (*MSTServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Put",
			Handler:    _MSTService_Put_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _MSTService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mst.proto",
}

// MSTManagerServiceClient is the client API for MSTManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MSTManagerServiceClient interface {
	Gossip(ctx context.Context, in *MSTGossipRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	GetNodes(ctx context.Context, in *MSTGetNodesRequest, opts ...grpc.CallOption) (*MSTGetNodesResponse, error)
}

type mSTManagerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMSTManagerServiceClient(cc grpc.ClientConnInterface) MSTManagerServiceClient {
	return &mSTManagerServiceClient{cc}
}

func (c *mSTManagerServiceClient) Gossip(ctx context.Context, in *MSTGossipRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/vulture.service.rpc.MSTManagerService/Gossip", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mSTManagerServiceClient) GetNodes(ctx context.Context, in *MSTGetNodesRequest, opts ...grpc.CallOption) (*MSTGetNodesResponse, error) {
	out := new(MSTGetNodesResponse)
	err := c.cc.Invoke(ctx, "/vulture.service.rpc.MSTManagerService/GetNodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MSTManagerServiceServer is the server API for MSTManagerService service.
type MSTManagerServiceServer interface {
	Gossip(context.Context, *MSTGossipRequest) (*empty.Empty, error)
	GetNodes(context.Context, *MSTGetNodesRequest) (*MSTGetNodesResponse, error)
}

// UnimplementedMSTManagerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMSTManagerServiceServer struct {
}

func (*UnimplementedMSTManagerServiceServer) Gossip(context.Context, *MSTGossipRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Gossip not implemented")
}
func (*UnimplementedMSTManagerServiceServer) GetNodes(context.Context, *MSTGetNodesRequest) (*MSTGetNodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodes not implemented")
}

func RegisterMSTManagerServiceServer(s *grpc.Server, srv MSTManagerServiceServer) {
	s.RegisterService(&_MSTManagerService_serviceDesc, srv)
}

func _MSTManagerService_Gossip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MSTGossipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MSTManagerServiceServer).Gossip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vulture.service.rpc.MSTManagerService/Gossip",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MSTManagerServiceServer).Gossip(ctx, req.(*MSTGossipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MSTManagerService_GetNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MSTGetNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MSTManagerServiceServer).GetNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vulture.service.rpc.MSTManagerService/GetNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MSTManagerServiceServer).GetNodes(ctx, req.(*MSTGetNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MSTManagerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "vulture.service.rpc.MSTManagerService",
	HandlerType: (*MSTManagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Gossip",
			Handler:    _MSTManagerService_Gossip_Handler,
		},
		{
			MethodName: "GetNodes",
			Handler:    _MSTManagerService_GetNodes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mst.proto",
}
