// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// MSTServiceClient is the client API for MSTService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MSTServiceClient interface {
	GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*MSTNode, error)
}

type mSTServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMSTServiceClient(cc grpc.ClientConnInterface) MSTServiceClient {
	return &mSTServiceClient{cc}
}

var mSTServiceGetNodeStreamDesc = &grpc.StreamDesc{
	StreamName: "GetNode",
}

func (c *mSTServiceClient) GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*MSTNode, error) {
	out := new(MSTNode)
	err := c.cc.Invoke(ctx, "/vulture.service.rpc.MSTService/GetNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MSTServiceService is the service API for MSTService service.
// Fields should be assigned to their respective handler implementations only before
// RegisterMSTServiceService is called.  Any unassigned fields will result in the
// handler for that method returning an Unimplemented error.
type MSTServiceService struct {
	GetNode func(context.Context, *GetNodeRequest) (*MSTNode, error)
}

func (s *MSTServiceService) getNode(_ interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return s.GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     s,
		FullMethod: "/vulture.service.rpc.MSTService/GetNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return s.GetNode(ctx, req.(*GetNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegisterMSTServiceService registers a service implementation with a gRPC server.
func RegisterMSTServiceService(s grpc.ServiceRegistrar, srv *MSTServiceService) {
	srvCopy := *srv
	if srvCopy.GetNode == nil {
		srvCopy.GetNode = func(context.Context, *GetNodeRequest) (*MSTNode, error) {
			return nil, status.Errorf(codes.Unimplemented, "method GetNode not implemented")
		}
	}
	sd := grpc.ServiceDesc{
		ServiceName: "vulture.service.rpc.MSTService",
		Methods: []grpc.MethodDesc{
			{
				MethodName: "GetNode",
				Handler:    srvCopy.getNode,
			},
		},
		Streams:  []grpc.StreamDesc{},
		Metadata: "service/rpc/mst.proto",
	}

	s.RegisterService(&sd, nil)
}
